FROM python:3.11-slim

WORKDIR /app

# Instalar dependências
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar o script
COPY keep_alive.py .

# Executar o script
CMD ["python", "keep_alive.py"]
